In [1]:
import cv2
import numpy as np
 
img_path=r"D:\Python DS\Computer Vision\Mai-Baba.jpg"
img = cv2.imread(img_path) # give numpy array
img = cv2.resize(img, (1280, 720))
 
cv2.imshow("Mai-Baba",img)

# text = "Mai-Baba" # image name
# org = (100, 200) #original
# font = cv2.FONT_HERSHEY_COMPLEX
# fontScale = 6
# color = (0,0,255)  #(B, G, R)
# thickness = 3
# lineType = cv2.LINE_AA
# bottomLeftOrigin = True #True for reverse image
 
# # Syntax>> cv2.putText(image, text, org, font, fontScale, color[, thickness[, lineType[, bottomLeftOrigin]]])
 
# img_text = cv2.putText(image, text, org, font, fontScale, color, thickness, lineType, bottomLeftOrigin=False)
 
# cv2.imshow("Text Image", img_text)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Split image using NumPy indexing


In [2]:
img.shape #height width and three color(b,g,r)

(720, 1280, 3)

In [3]:
img[:,:,0]  # b=0 ,g=1 ,r=2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [4]:
img[:,:,1]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [5]:
img[:,:,2]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

# Split image using cv2.split()

In [9]:
b, g, r = cv2.split(img)

In [10]:
b
b.shape


(720, 1280)

# Time Calculation to split Image

For Split fucntion

In [11]:
import time
 
start_time = time.time()
 
for i in range(100):
    r, g, r = cv2.split(img)
     
end_time = time.time()
 
print("Total time taken to split 100 images: ", end_time - start_time)

Total time taken to split 100 images:  0.45373964309692383


For Numpy Indexing

In [12]:
import time
 
start_time = time.time()
 
for i in range(100):
    b = img[:, :, 0]
    g = img[:, :, 1]
    r = img[:, :, 2]
     
end_time = time.time()
 
print("Total time taken to split 100 images: ", end_time - start_time)

Total time taken to split 100 images:  0.0009992122650146484


# Show single channel

In [16]:
import cv2
 
img_path=r"D:\Python DS\Computer Vision\Mai-Baba.jpg"
 
img = cv2.imread(img_path)
img = cv2.resize(img, (400, 400))
 
cv2.imshow("Model Blue Image", img[:,:,0])
cv2.imshow("Model Green Image", img[:,:,1])
cv2.imshow("Model Red Image", img[:,:,2])
 
cv2.waitKey(0)

-1

# Merge Image

In [17]:
img_merge = cv2.merge([b,g,r])

In [19]:
import cv2
 
img_path=r"D:\Python DS\Computer Vision\Mai-Baba.jpg" 
img = cv2.imread(img_path)
img = cv2.resize(img, (400, 400))
 
b, g, r = cv2.split(img)
 
 
img_merge = cv2.merge([b,g,r])
 
cv2.imshow("Model Blue Image", b)
cv2.imshow("Model Green Image", g)
cv2.imshow("Model Red Image", r)
 
cv2.imshow("Merge Model Image", img_merge)
 
cv2.waitKey(0)
cv2.destroyAllWindows()